on:
    workflow_call:
      inputs:
        APP_NAME:
            required: true
            type: string
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        # Check out the code
        - name: Checkout Code
          uses: actions/checkout@v3

        # Login to Docker Registry
        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        # Build and Push Docker Image
        - name: Build and Push Docker Image
          run: |
            REPO_NAME=${{ inputs.APP_NAME }}
            REPO_NAME_ONLY=${REPO_NAME##*/}
            docker build -t ${{ secrets.DOCKER_USERNAME }}/$REPO_NAME_ONLY .
            docker push ${{ secrets.DOCKER_USERNAME }}/$REPO_NAME_ONLY
  